name: Flutter CI

on:
  push:
    branches:
      - test

env:
  flutter_version: "1.22.x"
  java_version: "12.x"

jobs:
  format-and-lint:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
