name: Caching Primes

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache Flutter
      id: cache-flutter
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/flutter
        key: foobar
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
